services:
  ocr-api:
    build: .
    container_name: ocr-api-service
    ports:
      - "5000:5000"
    environment:
      - HOST=0.0.0.0
      - PORT=5000
      - DEBUG=False
      - MAX_QUEUE_SIZE=10
      - MAX_WORKERS=2
      - TIMEOUT_SECONDS=30
      - OCR_LANGUAGES=es,en
      - USE_GPU=False
      - LOG_LEVEL=INFO
      - LOG_FILE=/app/logs/ocr_service.log
      - LOG_MAX_SIZE=10485760
      - LOG_BACKUP_COUNT=5
      - MAX_IMAGE_SIZE_MB=10
      - ENABLE_API_KEY=True
      - API_KEY=${API_KEY:-your_secure_api_key_here}
      - CLEANUP_INTERVAL=300
    volumes:
      - ./logs:/app/logs
      - ./.env:/app/.env:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'
        reservations:
          memory: 1G
          cpus: '0.5'
    networks:
      - ocr-network

networks:
  ocr-network:
    driver: bridge